[package]
name = "check_if_every_row_and_column_contains_all_numbers"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="check_if_every_row_and_column_contains_all_numbers.rs"

[dependencies]
