[package]
name = "least_number_of_unique_integers_after_k_removals"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="least_number_of_unique_integers_after_k_removals.rs"

[dependencies]
