[package]
name = "the_k_th_lexicographical_string_of_all_happy_strings_of_length_n"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="the_k_th_lexicographical_string_of_all_happy_strings_of_length_n.rs"

[dependencies]
