[package]
name = "construct_binary_tree_from_preorder_and_postorder_traversal"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="construct_binary_tree_from_preorder_and_postorder_traversal.rs"

[dependencies]
utils = { path = "../utils" }