[package]
name = "minimum_operations_to_make_array_values_equal_to_k"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="minimum_operations_to_make_array_values_equal_to_k.rs"

[dependencies]
