[package]
name = "delete_nodes_from_linked_list_present_in_array"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="delete_nodes_from_linked_list_present_in_array.rs"

[dependencies]
utils = { path = "../utils" }
