[package]
name = "minimum_number_of_operations_to_sort_a_binary_tree_by_level"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="minimum_number_of_operations_to_sort_a_binary_tree_by_level.rs"

[dependencies]
utils = { path = "../utils" }
