[package]
name = "reverse_substrings_between_each_pair_of_parentheses"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="reverse_substrings_between_each_pair_of_parentheses.rs"

[dependencies]
