[package]
name = "smallest_subtree_with_all_the_deepest_nodes"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="smallest_subtree_with_all_the_deepest_nodes.rs"

[dependencies]
utils = { path = "../utils" }