[package]
name = "find_the_longest_substring_containing_vowels_in_even_counts"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="find_the_longest_substring_containing_vowels_in_even_counts.rs"

[dependencies]
