[package]
name = "double_a_number_represented_as_a_linked_list"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="double_a_number_represented_as_a_linked_list.rs"

[dependencies]
utils = { path = "../utils" }