[package]
name = "construct_the_lexicographically_largest_valid_sequence"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="construct_the_lexicographically_largest_valid_sequence.rs"

[dependencies]
