[package]
name = "minimum_recolors_to_get_k_consecutive_black_blocks"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="minimum_recolors_to_get_k_consecutive_black_blocks.rs"

[dependencies]
