[package]
name = "minimum_number_of_removals_to_make_mountain_array"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="minimum_number_of_removals_to_make_mountain_array.rs"

[dependencies]
