[package]
name = "remove_zero_sum_consecutive_nodes_from_linked_list"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="remove_zero_sum_consecutive_nodes_from_linked_list.rs"

[dependencies]
utils={path="../utils"}