[package]
name = "determine_whether_matrix_can_be_obtained_by_rotation"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="determine_whether_matrix_can_be_obtained_by_rotation.rs"

[dependencies]
