[package]
name = "maximum_number_of_integers_to_choose_from_a_range_i"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
path="maximum_number_of_integers_to_choose_from_a_range_i.rs"

[dependencies]
